### ISSUE TITLE
nexusmods needs recompiled binary for skse 2.0.17

### ISSUE THREAD

**Issue by myk002** [Ryan-rsm-McKenzie/YesImSure#2]
in skse64.log: plugin C:\...\Data\SKSE\Plugins\\YesImSure.dll (00000001 YesImSure 00000001) reported as incompatible during query

Likely just needs a recompile and an update at https://www.nexusmods.com/skyrimspecialedition/mods/24898

**Comment by Ryan-rsm-McKenzie** [comment]
I'm well aware the mod is out of date. This page is for actual issues related to the mod. Don't abuse it.
